version: '3'

services:
  kafka-1:
    image: confluentinc/cp-kafka:7.8.0
    container_name: kafka-1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:29092,EXTERNAL://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    depends_on:
      - kafka-1
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-1:29092
    ports:
      - "8989:8080"
    restart: always

  #  eureka:

  chatting-1:
    container_name: chatting-1
    build:
      context: .
      dockerfile: ./distributed-chat-system-chatting/Dockerfile
  #    depends_on:
  #      - eureka

  chatting-2:
    container_name: chatting-2
    build:
      context: .
      dockerfile: ./distributed-chat-system-chatting/Dockerfile

  chatting-3:
    container_name: chatting-3
    build:
      context: .
      dockerfile: ./distributed-chat-system-chatting/Dockerfile