version: '3'

services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka-1:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper-1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:29092,EXTERNAL://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    depends_on:
      - kafka-1
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-1:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper-1:2181
    ports:
      - "8989:8080"
    restart: always

  chatting-1:
    image: quddlf410/dcs-chatting
    build:
      context: /distributed-chat-system-chatting
      dockerfile: Dockerfile
    ports:
      - "7777:7777"
    environment:
      - SERVER_PORT=7777

  chatting-2:
    image: quddlf410/dcs-chatting
    build:
      context: /distributed-chat-system-chatting
      dockerfile: Dockerfile
    ports:
      - "7778:7778"
    environment:
      - SERVER_PORT=7778

  chatting-3:
    image: quddlf410/dcs-chatting
    build:
      context: /distributed-chat-system-chatting
      dockerfile: Dockerfile
    ports:
      - "7779:7779"
    environment:
      - SERVER_PORT=7779