spring:
  config:
    activate:
      on-profile: default

  application:
    name: api-gateway

  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: client-api
          uri: lb://CLIENT-API
          predicates:
            - Path=/v1/**
        - id: chatting
          uri: lb:ws://CHATTING
          predicates:
            - Path=/websocket/**
#          filters:
#            - name: ChattingRoutingFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7710/eureka/

  instance:
#    lease-renewal-interval-in-seconds: 5 # 하트비트가 수신되지 않으면 서비스 등록 해제 (default: 30s)
#    lease-expiration-duration-in-seconds: 15 # 하트비트가 수신되지 않으면 서비스 등록 해제 (default: 90s)

---

spring:
  config:
    activate:
      on-profile: dev

---

spring:
  config:
    activate:
      on-profile: stage

---

spring:
  config:
    activate:
      on-profile: prod