spring:
  config:
    activate:
      on-profile: default

  session:
    store-type: redis
    redis:
      namespace: distributed-chat-system
    timeout: 43200m # 세션 만료 기한: 30일 = 43200m

service-discovery:
  url: http://localhost:7710/

---

spring:
  config:
    activate:
      on-profile: dev

---

spring:
  config:
    activate:
      on-profile: stage

---

spring:
  config:
    activate:
      on-profile: prod