spring:
  config:
    activate:
      on-profile: default

  session:
    store-type: redis

service-discovery:
  url: http://localhost:7710/

---

spring:
  config:
    activate:
      on-profile: dev

---

spring:
  config:
    activate:
      on-profile: stage

---

spring:
  config:
    activate:
      on-profile: prod