spring:
  config:
    activate:
      on-profile: default

  session:
    store-type: redis

---

spring:
  config:
    activate:
      on-profile: dev

---

spring:
  config:
    activate:
      on-profile: stage

---

spring:
  config:
    activate:
      on-profile: prod