spring:
  config:
    activate:
      on-profile: default

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chat?serverTimezone=Asia/Seoul&characterEncoding=utf-8
    username: ENC(Or4UtdD6fHHXS07D9lucmg==)
    password: ENC(Or4UtdD6fHHXS07D9lucmg==)

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        auto_quote_keyword: true

---

spring:
  config:
    activate:
      on-profile: docker

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-container:3306/chat?serverTimezone=Asia/Seoul&characterEncoding=utf-8
    username: ENC(Or4UtdD6fHHXS07D9lucmg==)
    password: ENC(Or4UtdD6fHHXS07D9lucmg==)

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        auto_quote_keyword: true

---

spring:
  config:
    activate:
      on-profile: dev

---

spring:
  config:
    activate:
      on-profile: stage

---

spring:
  config:
    activate:
      on-profile: prod