spring:
  config:
    activate:
      on-profile: default

  cloud:
    stream:
      function:
        definition: domainEventString; domainEventModel;

      kafka:
        binder:
          brokers: localhost:9092
          configuration:
            auto.offset.reset: earliest
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value.deserializer: org.apache.kafka.common.serialization.StringDeserializer

      bindings:
        domainEventString-in-0:
          content-type: text/plain
          destination: domain-event-string
          group: consumer-group-string
        domainEventString-out-0:
          destination: domain-event-string
          group: consumer-group-string
        domainEventModel-in-0:
          destination: domain-event-model
          group: consumer-group-model
        domainEventModel-out-0:
          destination: domain-event-model
          group: consumer-group-model

---

spring:
  config:
    activate:
      on-profile: dev

---

spring:
  config:
    activate:
      on-profile: stage

---

spring:
  config:
    activate:
      on-profile: prod